name: Release Helm Chart and Notify
description: Release Helm chart and notify on Mattermost
inputs:
  HELM_VERSION:
    description: 'Helm version to use'
    required: true
    default: '3.12.3'
  HELM_DEPENDENCIES:
    description: 'Helm dependencies'
    required: false
  INDEX_DIR:
    description: 'Index directory'
    required: true
    default: '.'
  CHARTS_DIR:
    description: 'Charts directory'
    required: true
    default: '.'
  TARGET_DIR:
    description: 'Target directory to release'
    required: true
    default: 'test'
  APP_ID:
    description: 'GitHub App ID'
    required: true
  PRIVATE_KEY:
    description: 'GitHub App private key'
    required: true
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notifications on Mattermost'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install packages
      run: |
        if which curl > /dev/null && which git > /dev/null && which jq > /dev/null; then
          echo "Packages are already installed"
        else
          sudo apt-get update && sudo apt-get install -y curl git jq
        fi
      shell: bash
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0
    - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
      id: app-token
      with:
        app-id: ${{ inputs.APP_ID }}
        private-key: ${{ inputs.PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: "helm-charts"
    - name: Get Helm chart version
      id: get-version
      env:
        CHARTS_DIR: ${{ inputs.CHARTS_DIR }}
      run: |
        echo VERSION=$(cat "$CHARTS_DIR/Chart.yaml" | grep -oPm 1 '(?<=version: ).*') >> $GITHUB_ENV
      shell: bash
    - name: Publish Helm chart
      uses: tylerauerbeck/helm-gh-pages@3227331903e1755121f8da35f2f4819d731449a5  # main as of 2026-03-13
      with:
        token: ${{ steps.app-token.outputs.token }}
        charts_dir: ${{ inputs.CHARTS_DIR }}
        index_dir: ${{ inputs.INDEX_DIR }}
        charts_url: https://imio.github.io/helm-charts/
        owner: IMIO
        repository: helm-charts
        branch: gh-pages
        target_dir: ${{ inputs.TARGET_DIR }}
        helm_version: ${{ inputs.HELM_VERSION }}
        dependencies: ${{ inputs.HELM_DEPENDENCIES }}
    - name : Send notification on Mattermost
      if: ${{ inputs.MATTERMOST_WEBHOOK_URL != '' }}
      env:
        WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        REPOSITORY: ${{ github.repository }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Success : $REPOSITORY has published a Helm release with version $VERSION. [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' \
          -d "$(jq -n --arg text "$MESSAGE" '{"text": $text}')" \
          "$WEBHOOK_URL"
      shell: bash
    - name : Send failure notification on Mattermost
      if: ${{ failure() && inputs.MATTERMOST_WEBHOOK_URL != '' }}
      env:
        WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        REPOSITORY: ${{ github.repository }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Error : Helm release has failed. (Repository: $REPOSITORY) [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' \
          -d "$(jq -n --arg text "$MESSAGE" '{"text": $text}')" \
          "$WEBHOOK_URL"
      shell: bash
