name: Run code analysis
description: Run code analysis and notify on Mattermost
inputs:
  BASE_DIR:
    description: 'Base directory'
    required: false
    default: ""
  CHECK:
    description: 'Check to be used'
    required: false
    default: ""
  PATH:
    description: 'Paths to be checked'
    required: false
    default: ""
  LOG_LEVEL:
    description: 'Log level'
    required: false
    default: "INFO"
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notifications on Mattermost, if not provided, notifications will not be sent'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install curl and jq
      run: |
        if which curl > /dev/null && which jq > /dev/null; then
          echo "curl and jq are already installed"
        else
          sudo apt-get update && sudo apt-get install -y curl jq
        fi
      shell: bash
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Run checks
      uses: IMIO/code-analysis-action@7969d657a907cb4d3b8e426481ba41a44cb57554  # main as of 2026-03-13
      with:
        check: ${{ inputs.CHECK }}
        path: ${{ inputs.PATH }}
        base_dir: ${{ inputs.BASE_DIR }}
        log_level: ${{ inputs.LOG_LEVEL }}
    - name : Send notification on Mattermost
      if: ${{ inputs.MATTERMOST_WEBHOOK_URL != '' }}
      env:
        WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        REPOSITORY: ${{ github.repository }}
        SERVER_URL: ${{ github.server_url }}
        REF_NAME: ${{ github.ref_name }}
        SHA: ${{ github.sha }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Code analysis has run successfully. ([Repository: $REPOSITORY]($SERVER_URL/$REPOSITORY), Branch: $REF_NAME, [View commit on GitHub]($SERVER_URL/$REPOSITORY/commit/$SHA)) [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' \
          -d "$(jq -n --arg text "$MESSAGE" '{"text": $text}')" \
          "$WEBHOOK_URL"
      shell: bash
    - name : Send failure notification on Mattermost
      if: ${{ failure() && inputs.MATTERMOST_WEBHOOK_URL != '' }}
      env:
        WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        REPOSITORY: ${{ github.repository }}
        SERVER_URL: ${{ github.server_url }}
        REF_NAME: ${{ github.ref_name }}
        SHA: ${{ github.sha }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Error : code analysis has failed. ([Repository: $REPOSITORY]($SERVER_URL/$REPOSITORY), Branch: $REF_NAME, [View commit on GitHub]($SERVER_URL/$REPOSITORY/commit/$SHA)) [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' \
          -d "$(jq -n --arg text "$MESSAGE" '{"text": $text}')" \
          "$WEBHOOK_URL"
      shell: bash
