name: Run code analysis
description: Run code analysis and notify on Mattermost
inputs:
  BASE_DIR:
    description: 'Base directory'
    required: false
    default: ""
  CHECK:
    description: 'Check to be used'
    required: false
    default: ""
  PATH:
    description: 'Paths to be checked'
    required: false
    default: ""
  LOG_LEVEL:
    description: 'Log level'
    required: false
    default: "INFO"
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notifications on Mattermost, if not provided, notifications will not be sent'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install curl and jq
      run: |
        if which curl > /dev/null && which jq > /dev/null; then
          echo "curl and jq are already installed"
        else
          sudo apt-get update && sudo apt-get install -y curl jq
        fi
      shell: bash
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run checks
      id: analysis
      uses: IMIO/code-analysis-action@7969d657a907cb4d3b8e426481ba41a44cb57554  # main as of 2026-03-13
      with:
        check: ${{ inputs.CHECK }}
        path: ${{ inputs.PATH }}
        base_dir: ${{ inputs.BASE_DIR }}
        log_level: ${{ inputs.LOG_LEVEL }}
    - name: Notify on Mattermost
      if: always()
      uses: imio/gha/mattermost-notify@v7
      with:
        MATTERMOST_WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        STATUS: ${{ steps.analysis.outcome == 'success' && 'success' || 'failure' }}
        TITLE: "Code Analysis"
        BODY: |
          **Repository:** [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})
          **Branch:** ${{ github.ref_name }}
          **Commit:** [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
