name: Run code analysis
description: Run code analysis and notify on Mattermost
inputs:
  BUILDOUT_COMMAND:
    description: 'Command to run buildout'
    required: true
    default: "buildout"
  BUILDOUT_CONFIG_FILE:
    description: 'Path to buildout configuration file'
    required: true
    default: "buildout.cfg"
  BUILDOUT_OPTIONS:
    description: 'Options to pass to buildout'
    required: false
    default: ""
  CACHE_KEY:
    description: 'Cache key'
    required: false
  INSTALL_DEPENDENCIES_COMMANDS:
    description: 'Commands to install dependencies'
    required: false
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notifications on Mattermost, if not provided, notifications will not be sent'
    required: false
  PYTHON_VERSION:
    description: 'Python version to use'
    required: true
    default: "3.13"
  TEST_COMMAND:
    description: 'Command to run tests'
    required: true
    default: "bin/test"
  UV_VERSION:
    description: 'Version of uv to use'
    required: true
    default: "0.7.13"
runs:
  using: 'composite'
  steps:
    - name: Install curl and git
      run: |
        if which curl > /dev/null && which git > /dev/null; then
          echo "curl and git are already installed"
        else
          sudo apt-get update && sudo apt-get install -y curl git
        fi
      shell: bash
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache eggs
      if: ${{ inputs.CACHE_KEY != '' }}
      uses: actions/cache@v4
      env:
        cache-name: cache-eggs
      with:
        path: ./eggs
        key: ${{ inputs.CACHE_KEY }}
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        version: ${{ inputs.UV_VERSION }}
    - name: Install dependencies
      if: ${{ inputs.INSTALL_DEPENDENCIES_COMMANDS != '' }}
      shell: bash
      run: |
        set +e
        IFS=$'\n' read -r -d '' -a commands <<< "${{ inputs.INSTALL_DEPENDENCIES_COMMANDS }}"
        for command in "${commands[@]}"; do
          echo "Running command: $command"
          $command
        done
    - name: Run buildout
      shell: bash
      run: |
        ${{ inputs.BUILDOUT_COMMAND }} -c ${{ inputs.BUILDOUT_CONFIG_FILE }} ${{ inputs.BUILDOUT_OPTIONS }} buildout:eggs-directory=./eggs
    - name: Run tests
      shell: bash
      run: |
        ${{ inputs.TEST_COMMAND }}
    - name : Send notification on Mattermost
      if: ${{ inputs.MATTERMOST_WEBHOOK_URL != '' }}
      run: |
        ESCAPED_COMMAND=$(echo ${{ inputs.TEST_COMMAND }} | sed 's/\\/\\\\/g')
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Test has run successfully. ([Repository: ${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}), Branch: ${{ github.ref_name }}, [View commit on GitHub](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}), Test command: $ESCAPED_COMMAND, Python version: ${{ inputs.PYTHON_VERSION }}) [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$MESSAGE\"}" ${{ inputs.MATTERMOST_WEBHOOK_URL }}
      shell: bash
    - name : Send failure notification on Mattermost
      if: ${{ failure() && inputs.MATTERMOST_WEBHOOK_URL != '' }}
      run: |
        ESCAPED_COMMAND=$(echo ${{ inputs.TEST_COMMAND }} | sed 's/\\/\\\\/g')
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Error : Test has failed. ([Repository: ${{ github.repository }}](${{ github.server_url }}/${{ github.repository }}), Branch: ${{ github.ref_name }}, [View commit on GitHub](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}), Test command: $ESCAPED_COMMAND, Python version: ${{ inputs.PYTHON_VERSION }}) [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$MESSAGE\"}" ${{ inputs.MATTERMOST_WEBHOOK_URL }}
      shell: bash