name: Notify on Mattermost
description: Send a notification on a Mattermost webhook
inputs:
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notification on Mattermost'
    required: true
  MESSAGE:
    description: 'Message to send on Mattermost'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install curl and jq
      run: |
        if which curl > /dev/null && which jq > /dev/null; then
          echo "curl and jq are already installed"
        else
          sudo apt-get update && sudo apt-get install -y curl jq
        fi
      shell: bash
    - name : Send notification on Mattermost
      env:
        WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        MESSAGE: ${{ inputs.MESSAGE }}
      run: |
        curl -i --fail-with-body -X POST -H 'Content-Type: application/json' \
          -d "$(jq -n --arg text "$MESSAGE " '{"text": $text}')" \
          "$WEBHOOK_URL"
      shell: bash
