name: Lint and Test Helm Chart and Notify
description: Lint and test Helm chart and notify on Mattermost
inputs:
  PYTHON_VERSION:
    description: 'Python version to use'
    required: true
    default: '3.10'
  HELM_VERSION:
    description: 'Helm version to use'
    required: true
    default: 'v3.12.3'
  HELM_RELEASE:
    description: 'Helm release name'
    required: true
    default: 'test'
  HELM_NAMESPACE:
    description: 'Helm namespace name'
    required: true
    default: 'test'
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notifications on Mattermost'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install packages
      run: |
        if which curl > /dev/null && which git > /dev/null && which wget > /dev/null && which jq > /dev/null; then
          echo "Packages are already installed"
        else
          sudo apt-get update && sudo apt-get install -y curl git wget jq
        fi
      shell: bash
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: ${{ inputs.HELM_VERSION }}
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        check-latest: true
    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1
    - name: Run chart-testing (lint)
      env:
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      run: ct lint --chart-dirs . --charts . --target-branch "$DEFAULT_BRANCH"
      shell: bash
    - name: Create kind cluster
      uses: helm/kind-action@v1.10.0
    - name: Run chart-testing (install)
    #  run: ct install --chart-dirs . --charts . --target-branch ${{ github.event.repository.default_branch }}
    # can't use it until https://github.com/helm/chart-testing/issues/310 is resolved
      env:
        HELM_RELEASE: ${{ inputs.HELM_RELEASE }}
        HELM_NAMESPACE: ${{ inputs.HELM_NAMESPACE }}
      run: helm install "$HELM_RELEASE"  . -f values.yaml --namespace "$HELM_NAMESPACE" --create-namespace
      shell: bash
    - name : Send notification on Mattermost
      if: ${{ inputs.MATTERMOST_WEBHOOK_URL != '' }}
      env:
        WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        REPOSITORY: ${{ github.repository }}
        REF_NAME: ${{ github.ref_name }}
        SHA: ${{ github.sha }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Success : helm lint and tests. (Repository: $REPOSITORY, Branch: $REF_NAME, Commit: $SHA) [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' \
          -d "$(jq -n --arg text "$MESSAGE" '{"text": $text}')" \
          "$WEBHOOK_URL"
      shell: bash
    - name : Send failure notification on Mattermost
      if: ${{ failure() && inputs.MATTERMOST_WEBHOOK_URL != '' }}
      env:
        WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
        REPOSITORY: ${{ github.repository }}
        REF_NAME: ${{ github.ref_name }}
        SHA: ${{ github.sha }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Error : helm lint and tests have failed. (Repository: $REPOSITORY, Branch: $REF_NAME, Commit: $SHA) [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' \
          -d "$(jq -n --arg text "$MESSAGE" '{"text": $text}')" \
          "$WEBHOOK_URL"
      shell: bash
