name: Trigger repository dispatch and notify on Mattermost
description: Trigger a repository dispatch event and optionally notify on Mattermost
inputs:
  REPOSITORY:
    description: 'Repository to trigger the dispatch event'
    required: true
  GIT_REFERENCE:
    description: 'Reference to trigger the event on'
    required: false
    default: 'main'
  INPUTS:
    description: 'Inputs to pass to the workflow'
    required: false
    default: '{}'
  WORKFLOW_FILENAME:
    description: 'Filename of the workflow to trigger'
    required: true
  APP_ID:
    description: 'GitHub App ID'
    required: true
  APP_PRIVATE_KEY:
    description: 'GitHub App private key'
    required: true
  REPOSITORY_OWNER:
    description: 'Owner of the repository'
    required: true
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notifications on Mattermost, if not provided, notifications will not be sent'
    required: false
runs:
  using: 'composite'
  steps:
  - name: Install curl and jq
    run: |
      if which curl > /dev/null ; then
        echo "curl is already installed"
      else
        sudo apt-get update && sudo apt-get install -y curl
      fi
      if which jq > /dev/null ; then
        echo "jq is already installed"
      else
        sudo apt-get update && sudo apt-get install -y jq
      fi
    shell: bash
  - uses: actions/create-github-app-token@v1
    id: app-token
    with:
      app-id: ${{ inputs.APP_ID }}
      private-key: ${{ inputs.APP_PRIVATE_KEY }}
      owner: ${{ inputs.REPOSITORY_OWNER}}
  - name: Trigger repository dispatch
    id: dispatch
    env:
      APP_TOKEN: ${{ steps.app-token.outputs.token }}
      REPOSITORY_OWNER: ${{ inputs.REPOSITORY_OWNER }}
      REPOSITORY: ${{ inputs.REPOSITORY }}
      WORKFLOW_FILENAME: ${{ inputs.WORKFLOW_FILENAME }}
      GIT_REFERENCE: ${{ inputs.GIT_REFERENCE }}
      INPUTS: ${{ inputs.INPUTS }}
    run: |
      PAYLOAD=$(jq -n --arg ref "$GIT_REFERENCE" --argjson inputs "$INPUTS" '{"ref": $ref, "inputs": $inputs}')
      curl -L \
      --fail-with-body \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $APP_TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "https://api.github.com/repos/$REPOSITORY_OWNER/$REPOSITORY/actions/workflows/$WORKFLOW_FILENAME/dispatches" \
      -d "$PAYLOAD"
    shell: bash
  - name: Notify on Mattermost
    if: always()
    uses: imio/gha/mattermost-notify@rework/mattermost-notifications
    with:
      MATTERMOST_WEBHOOK_URL: ${{ inputs.MATTERMOST_WEBHOOK_URL }}
      STATUS: ${{ steps.dispatch.outcome == 'success' && 'success' || 'failure' }}
      TITLE: "Repository Dispatch"
      BODY: |
        **Repository:** ${{ inputs.REPOSITORY }}
        **Branch:** ${{ github.ref_name }}
