name: Call rundeck job and notify
description: Call a rundeck job and notify on Mattermost
inputs:
  RUNDECK_URL:
    description: 'URL of the Rundeck server'
    required: true
  RUNDECK_TOKEN:
    description: 'Auth token to call Rundeck job'
    required: true
  RUNDECK_JOB_ID:
    description: 'ID of the Rundeck job to call'
    required: true
  MATTERMOST_WEBHOOK_URL:
    description: 'Webhook URL to send notifications on Mattermost, if not provided, notifications will not be sent'
    required: false
  RUNDECK_PARAMETERS:
    description: 'Parameters to pass to the Rundeck job'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl
      shell: bash
    - name: Call Rundeck job
      run: |
        curl -i --fail-with-body ${{ inputs.RUNDECK_PARAMETERS }} -H "X-Rundeck-Auth-Token: ${{ inputs.RUNDECK_TOKEN }}" ${{ inputs.RUNDECK_URL }}/api/18/job/${{ inputs.RUNDECK_JOB_ID }}/run/ -o rundeck-response.json
        JOB_NAME=$(jq -r .job.name rundeck-response.json)
        JOB_EXECUTION_PERMALINK=$(jq -r .permalink rundeck-response.json)
      shell: bash
    - name : Send notification on Mattermost
      if: ${{ inputs.MATTERMOST_WEBHOOK_URL != '' }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="rundeck job [$JOB_NAME]($JOB_EXECUTION_PERMALINK) has been successfully called . [Click here to see job on GitHub]($JOB_URL) "
        curl -i -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$MESSAGE\"}" ${{ inputs.MATTERMOST_WEBHOOK_URL }}
      shell: bash
    - name : Send failure notification on Mattermost
      if: ${{ failure() && inputs.MATTERMOST_WEBHOOK_URL != '' }}
      run: |
        JOB_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        MESSAGE="Error : cannot call rundeck job [$JOB_NAME]($JOB_EXECUTION_PERMALINK). [Click here to see job on GitHub]($JOB_URL)"
        curl -i -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$MESSAGE\"}" ${{ inputs.MATTERMOST_WEBHOOK_URL }}
      shell: bash