name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0
    - name: Get Main version
      id: vars
      run: |
        echo ${{ github.ref_name }}
        main_version=$(echo "v3.1.1" | cut -d '.' -f 1)
        echo "Main version: $main_version"
        echo "main_version=$main_version" >> "$GITHUB_OUTPUT"
        echo $main_version
    - name: Update Main version
      if: ${{ !env.ACT }} # do not run locally
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -f ${{ steps.vars.outputs.main_version }} ${{ github.ref_name }}
        git push origin ${{ steps.vars.outputs.main_version }} --force